// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMG.Data;

#nullable disable

namespace WebMG.Migrations
{
    [DbContext(typeof(MGDbContext))]
    [Migration("20241007161322_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebMG.Models.AttendCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpId1")
                        .HasColumnType("int");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SchoolDay")
                        .HasColumnType("date");

                    b.Property<int>("StuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmpId1");

                    b.HasIndex("ParId");

                    b.HasIndex("StuId");

                    b.ToTable("AttendCards");
                });

            modelBuilder.Entity("WebMG.Models.Emp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pin")
                        .HasColumnType("int");

                    b.Property<bool>("Teach")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Emps");
                });

            modelBuilder.Entity("WebMG.Models.Fam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParId")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParId");

                    b.ToTable("Fams");
                });

            modelBuilder.Entity("WebMG.Models.Par", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Par2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pars");
                });

            modelBuilder.Entity("WebMG.Models.Stu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ClassCategory")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Disenroll")
                        .HasColumnType("date");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FamId")
                        .HasColumnType("int");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FamId");

                    b.ToTable("Stus");
                });

            modelBuilder.Entity("WebMG.Models.TimeCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Finish")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimeCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.ToTable("TimeCards");
                });

            modelBuilder.Entity("WebMG.Models.AttendCard", b =>
                {
                    b.HasOne("WebMG.Models.Emp", "Emp")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebMG.Models.Emp", null)
                        .WithMany("AttendCards")
                        .HasForeignKey("EmpId1");

                    b.HasOne("WebMG.Models.Par", "Par")
                        .WithMany("AttendCards")
                        .HasForeignKey("ParId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebMG.Models.Stu", "Stu")
                        .WithMany("AttendCards")
                        .HasForeignKey("StuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emp");

                    b.Navigation("Par");

                    b.Navigation("Stu");
                });

            modelBuilder.Entity("WebMG.Models.Fam", b =>
                {
                    b.HasOne("WebMG.Models.Par", "Par")
                        .WithMany()
                        .HasForeignKey("ParId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Par");
                });

            modelBuilder.Entity("WebMG.Models.Stu", b =>
                {
                    b.HasOne("WebMG.Models.Fam", null)
                        .WithMany("Stus")
                        .HasForeignKey("FamId");
                });

            modelBuilder.Entity("WebMG.Models.TimeCard", b =>
                {
                    b.HasOne("WebMG.Models.Emp", "Emp")
                        .WithMany("TimeCards")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("WebMG.Models.Emp", b =>
                {
                    b.Navigation("AttendCards");

                    b.Navigation("TimeCards");
                });

            modelBuilder.Entity("WebMG.Models.Fam", b =>
                {
                    b.Navigation("Stus");
                });

            modelBuilder.Entity("WebMG.Models.Par", b =>
                {
                    b.Navigation("AttendCards");
                });

            modelBuilder.Entity("WebMG.Models.Stu", b =>
                {
                    b.Navigation("AttendCards");
                });
#pragma warning restore 612, 618
        }
    }
}
